### ISSUE TITLE
cannot load such file

### ISSUE THREAD

**Issue by Zawadidone** [rastating/joomlavs#35]
```
ruby joomlavs.rb

Traceback (most recent call last):
	6: from joomlavs.rb:22:in `<main>'
	5: from joomlavs.rb:22:in `require_relative'
	4: from /home/zawadi/joomlavs/lib/joomlavs/helper.rb:22:in `<top (required)>'
	3: from /home/zawadi/joomlavs/lib/joomlavs/helper.rb:22:in `require_relative'
	2: from /home/zawadi/joomlavs/lib/joomlavs/output.rb:16:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- colorize (LoadError)
```

**Comment by rastating** [comment]
You need to install the gems using bundler. Run `gem install bundler && bundle install` to install both bundler and the gems from the Gemfile

**Comment by rastating** [comment]
I've just noticed there is a typo in the instructions in the README, bundler shouldn't have been run with `sudo` - have you tried running it without `sudo`?

**Comment by Zawadidone** [comment]
Thanks that was the problem.
