### ISSUE TITLE
joomlavs Not working

### ISSUE THREAD

**Issue by MindPatch** [rastating/joomlavs#37]
when i start joomlavs using this command :  

````
ruby joomlavs.rb
````
and input this error 

````
Traceback (most recent call last):
	2: from ./joomlavs.rb:20:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- slop (LoadError)

````

my os : Kali Linux

**Comment by rastating** [comment]
You need to install the dependencies - see step 3 of this page: https://github.com/rastating/joomlavs#how-to-install

**Comment by knassar702** [comment]
i install it before run the tool

**Comment by MindPatch** [comment]
ok worked .. Thanks
